In [ ]:
import pandas as pd
import numpy as np

# pandas : 데이터 처리 및 분석
# numpy : 과학계산 및 숫자계산
    # - C, C++ 기반으로 작성되어 있어 빠르다.
    # - 중간에 C를 불러 쓸 수 있는 api 이용하여 파이썬 환경에서 사용
# scipy : 과학계산 및 계산 통계
# tensorflow : 머신러닝, 딥러닝
# keras : 신경망, 딥러닝
# matplotlib, seaborn, plotly : 시각화

# numpy 배열
# numpy 배열 1차(백터), 2차(매트릭스)

# 머신러닝에서 사용되는 데이터 구조


In [ ]:
# 1차원 배열

arr1 = np.array([1, 2, 3]) # 이것은 벡터다.
arr1

array([1, 2, 3])

In [3]:
arr1.shape

(3,)

In [6]:
# 2차원 배열(매트릭스)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
arr3 = np.array([[1, 2, 3]])
print(arr3)
print(arr3.shape)

[[1 2 3]]
(1, 3)


In [ ]:
# 차원 확인
print("차원", arr1.ndim)
print("차원", arr2.ndim)
print("차원", arr3.ndim) 

차원 1
차원 2
차원 2


In [11]:
list1 = [1, 2, 3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [13]:
print(arr1.dtype)
print(type(arr1))

int64
<class 'numpy.ndarray'>


In [14]:
arr1.astype("float64")

array([1., 2., 3.])

## 넘파이 배열 생성 함수

In [ ]:
np.arange(10) # 해당 입력한 숫자만큼길이의 리스트 생성(오름차순) 또는



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10) # 5부터 시작해서 10까지의 리스트

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 10, 2) # 1부터 10까지, 2간격으로

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros(5) # 0으로 채운 리스트 생성 len:5

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3), dtype='int64') # 2차원의 리스트 int 데이터를 넣는 생성

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((3, 2, 3), dtype='int64') # 3차원도 가능

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [ ]:
np.ones(5) # 1로 채우는 리스트

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty(4) # 임의로 생성된 값

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.19880322e-311])

In [27]:
np.empty((3,4), dtype='int64')

array([[      2426432949800,                  64,                   0,
                          0],
       [  30962724179542016, 3474587809873146935, 4121133838459036771,
        7233172845200893493],
       [4122591601899287351, 3546922503101833785, 3486457020695262007,
        7018406166710465588]])

In [28]:
np.full((3, 4), 7) # 3열 4행의 리스트에 7로 채우기

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
np.eye(3) # 단위행렬 생성 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(6, k=-1)

array([[0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [ ]:
np.linspace(1, 10, 5) # 1에서 10까지 일정한 간격의 숫자를 5개 생성

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.random.rand(2, 3) # 0~1 사이의 랜덤한 수를 2행 3열로 생성

array([[0.95396817, 0.56674805, 0.48542797],
       [0.94234172, 0.72118788, 0.55927426]])

In [ ]:
np.random.randn() # 정규분포표로 샘플링 된 랜덤 값

0.2040466622708553

In [39]:
np.random.randn(5) # 정규분포표로 샘플링 된 랜덤 값 5개 생성

array([ 0.85864807,  0.8398454 , -1.19937219, -1.66807074,  0.65873447])

In [ ]:
np.random.randint(1, 10, 5) # 1에서 10 사이의 숫자를 5개 생성

array([3, 2, 1, 7, 3], dtype=int32)

In [ ]:
np.random.seed(25) # 마인크래프트 맵 마냥 정해진 seed가 있음.
np.random.randint(1, 100, (3,5)) # 1에서 100 사이의 난수를 3행 5열로 생성

array([[ 5, 63, 91, 16, 62],
       [24, 45, 51,  9, 29],
       [ 5, 90, 32, 70,  2]], dtype=int32)

In [ ]:
np.random.choice(100, (3, 4)) # 랜덤한 0~99 까지의 난수를 3행 4열로 생성

array([[78, 11, 35, 28],
       [80, 50, 54, 37],
       [44, 57, 56, 20]], dtype=int32)

In [ ]:
arr1 = np.array([1, 23, 1.5, 2.6, 4.9])
np.random.choice(arr1, (2, 2)) # 랜덤한 수를 arr1에있는 수에서 가져와 2행 2열로 생성


array([[1.5, 2.6],
       [4.9, 1. ]])

In [132]:
np.random.choice(arr1, (2, 2), replace=False) # 동일하나 중복을 허용하지 않음

array([[4.9, 2.6],
       [1. , 1.5]])

In [135]:
# 인덱싱, 슬라이싱

arr1 = np.arange(1, 10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2 = arr1.reshape(3, 3) # arr1 리스트를 3행 3열, 즉 1차원 -> 2차원으로 변환.
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1[3] # 당연히 리스트니깐 인덱싱이랑 슬라이싱은 됨
arr1[:3]

array([1, 2, 3])

In [ ]:
# 다차원 리스트 인덱싱 or 슬라이싱 하는 방법 
arr2[0:2, 0:1] # 첫번째 축에서 0~2까지, 두번째 축에서 0~1까지를 슬라이싱

array([[1],
       [4]])

In [ ]:
# 불린 인덱싱 방법
arr1[arr1 % 2 == 0] # 배열 내에서 2로 나눌 때 나머지가 0 인 값들만 고르기

array([2, 4, 6, 8])

In [ ]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[1,1,1], [2,2,2]])

x + y # numpy로 생성한 리스트는 같은 행 열 축에 해당하는 데이터들끼리 연산이 바로 됨
x - y
x / y
x * y # or  np.multiply(x, y) 


array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [ ]:
t1 = [[1,2,3], [4,5,6]]
t2 = [[1,1,1], [2,2,2]]
t1 + t2 # 일반적인 방법으로 생성한 그냥 리스트는 + 를 이어 붙히는 개념으로만 붙게 됨

[[1, 2, 3], [4, 5, 6], [1, 1, 1], [2, 2, 2]]

In [ ]:
np.mean(x) 
np.var(x)
# 집계함수도 있음

np.float64(2.9166666666666665)